# config/cucumber.yml
##YAML Template
---
html_report: --format progress --format html --out=features_report.html  
bvt: --tags @bvt
testers: --require features/step_definitions --require features/support --require features/example/steps --require features/example/support --color
